//! Rust-side parity tests: verifies that `apply_moves` returns FENs that are
//! internally consistent (parse → re-serialize round-trip) across 100 deterministic
//! game traces generated by the crate itself.
//!
//! Gated on `#[cfg(feature = "impl")]` — run with `cargo test --features impl`.

#![allow(clippy::unwrap_used, clippy::expect_used)]

#[cfg(feature = "impl")]
mod parity {
    use purechess_engine::{apply_moves, legal_moves};
    use shakmaty::{CastlingMode, EnPassantMode, fen::Fen, Position};

    const STARTPOS: &str = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

    /// Build a deterministic game by cycling through legal moves with a seed-based index.
    fn deterministic_ucis(start: &str, plies: usize, seed: usize) -> Vec<String> {
        let mut ucis: Vec<String> = Vec::new();
        let mut fen = start.to_string();

        for i in 0..plies {
            let moves = legal_moves(&fen).unwrap_or_default();
            if moves.is_empty() {
                break;
            }
            let idx = (i.wrapping_mul(7).wrapping_add(seed.wrapping_mul(13))) % moves.len();
            let m = &moves[idx];
            ucis.push(m.uci.clone());

            // Advance FEN via apply_moves (single move)
            let uci_slice: Vec<&str> = ucis.iter().map(|s| s.as_str()).collect();
            match apply_moves(start, &uci_slice) {
                Ok(state) => {
                    fen = state.fen;
                    if state.result.is_some() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }

        ucis
    }

    /// Verify that `apply_moves` returns a valid, round-trippable FEN.
    fn assert_fen_round_trips(fen: &str, game_idx: usize, ply: usize) {
        let parsed: Fen = fen
            .parse()
            .unwrap_or_else(|e| panic!("game {game_idx} ply {ply}: apply_moves returned invalid FEN '{fen}': {e}"));

        let pos = parsed
            .into_position::<shakmaty::Chess>(CastlingMode::Standard)
            .unwrap_or_else(|e| panic!("game {game_idx} ply {ply}: FEN '{fen}' failed into_position: {e}"));

        let roundtrip = Fen::from_position(pos, EnPassantMode::Legal).to_string();

        assert_eq!(
            fen, roundtrip,
            "game {game_idx} ply {ply}: FEN round-trip failed\n  got:  {fen}\n  want: {roundtrip}",
        );
    }

    #[test]
    fn apply_moves_fen_consistency_100_games() {
        for i in 0..100_usize {
            let plies = 10 + (i % 40); // 10–49 plies per game
            let ucis = deterministic_ucis(STARTPOS, plies, i);

            if ucis.is_empty() {
                continue;
            }

            // Apply the full sequence and verify FEN round-trips at each prefix
            for ply in 1..=ucis.len() {
                let uci_slice: Vec<&str> = ucis[..ply].iter().map(|s| s.as_str()).collect();
                let state = apply_moves(STARTPOS, &uci_slice)
                    .unwrap_or_else(|e| panic!("game {i} ply {ply}: apply_moves error: {e}"));

                assert_fen_round_trips(&state.fen, i, ply);

                // Per-move fenAfter fields must also round-trip
                for m in &state.moves {
                    assert_fen_round_trips(&m.fen_after, i, m.ply as usize);
                }

                if state.result.is_some() {
                    break;
                }
            }
        }
    }

    #[test]
    fn legal_moves_deterministic_for_same_fen() {
        // legal_moves should return the same set when called twice on the same FEN
        for i in 0..20_usize {
            let ucis = deterministic_ucis(STARTPOS, 10 + i, i);
            let uci_slice: Vec<&str> = ucis.iter().map(|s| s.as_str()).collect();
            let state = apply_moves(STARTPOS, &uci_slice).expect("apply_moves ok");
            let fen = &state.fen;

            let moves_a = legal_moves(fen).expect("legal_moves a ok");
            let moves_b = legal_moves(fen).expect("legal_moves b ok");

            assert_eq!(
                moves_a.len(),
                moves_b.len(),
                "game {i}: legal_moves count differs between calls"
            );
            for (ma, mb) in moves_a.iter().zip(moves_b.iter()) {
                assert_eq!(ma.uci, mb.uci, "game {i}: move uci differs");
                assert_eq!(ma.san, mb.san, "game {i}: move san differs");
            }
        }
    }
}
