export { GameShell, type GameShellProps } from './game-shell';
export { GameTopBar, type GameTopBarProps } from './game-top-bar';
export { BoardColumn, type BoardColumnProps } from './board-column';
export { PlayerStrip, type PlayerStripProps } from './player-strip';
export { CapturedMaterial, type CapturedMaterialProps } from './captured-material';
export { GameRail, type GameRailProps } from './game-rail';
export { MovePanel, type MovePanelMove, type MovePanelProps } from './move-panel';
export { BoardControlBar, type BoardControlBarProps } from './board-control-bar';
export { GameErrorState, type GameErrorStateProps } from './game-error-state';
export { MoveErrorNotice, type MoveErrorNoticeProps } from './move-error-notice';
